tree: Events
era: 2018
lumi: 59740.565201546
envPath: /cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/setup.sh
jobDir: /afs/cern.ch/work/g/gsaha/public/ChargedHiggsAnalysis
exeToRun: /afs/cern.ch/work/g/gsaha/public/ChargedHiggsAnalysis/Analysis/multileptonMVA_DY
outDir: /eos/user/g/gsaha/Exotic/ChargedHiggsAnalysis
commonInfo:
  - readGenInfo 0
  - dumpGenInfo 0
  - readTrigObject 0
  - readPFObject 1
  - useLumiWt 1
  - dumpEventMax 10
  - logOption 0
  - maxEvent -1
  - nFiles -1
  - verbose 0
mvaInfo:
  - readMVA 0
  - MVAnetwork BDT_nT1500_D2_nC100_ns5
  - MVAxmlFile TMVAClassification_BDT_nT1500_D2_nC100_ns5.weights.xml
skimInfo:
  - createMVATree 0
cutLists:
  #- muonCutList eta=2.4 pt=5. dxy=0.2 dz=0.5 SIP3D=8. ptFake=10 reliso=0.15
  - muonCutList eta=2.4 pt=5. dxy=0.5 dz=1.0 SIP3D=4. ptFake=10 reliso=0.35
  #- electronCutList pt=7. eta=2.5 dxy=0.05 dz=0.1 SIP3D=8. ptFake=10
  - electronCutList pt=7. eta=2.5 dxy=0.5 dz=1.0 SIP3D=4. ptFake=10 reliso=0.35
  - jetCutList eta=2.5 pt=25. lbjetScore=0.0521 bjetScore=0.3033 deltaR=0.8
  - tauCutList eta=2.4 pt=20. dz=0.2 dxy=0.1
  - fatJetCutList eta=2.4 pt=200. subJetPt=20  subJetEta=2.4 msoftdropMin=30 msoftdropMax=210 fjetRatio=0.75 bSubJetPt=30 bSubJetScore=0.4941
### Do not use HLT at the beginning of the HLT path name ###
HLT_DoubleMuon:
  - Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8
HLT_DoubleEG:
  - Ele23_Ele12_CaloIdL_TrackIdL_IsoVL
  - DoubleEle25_CaloIdL_MW
HLT_MuonEG:
  - Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
  - Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
  - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL
HLT_SingleMuon:
  - IsoMu24
  - IsoMu27
HLT_SingleElectron:
  - Ele32_WPTight_Gsf
HLT_SingleElectronForFake:
  - Ele8_CaloIdM_TrackIdM_PFJet30
  - Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30
  - Ele17_CaloIdM_TrackIdM_PFJet30
HLT_SingleMuonForFake:
  - Mu8_TrkIsoVVL
  - Mu17_TrkIsoVVL
ScaleFactorsInfo:
  ### MuonID-ScaleFactors
  - muonIdSFRootFile /afs/cern.ch/work/g/gsaha/public/ChargedHiggsAnalysis/Analysis/data/POG_SFs/2018/Muon/RunABCD_SF_ID.root
  - looseMuonIdSFhistName NUM_LooseID_DEN_TrackerMuons_pt_abseta_syst
  - medMuonIdSFhistName NUM_MediumID_DEN_TrackerMuons_pt_abseta_syst
  - tightMuonIdSFhistName NUM_TightID_DEN_TrackerMuons_pt_abseta_syst
  ### MuonISO-ScaleFactors 
  - muonTightIsoSFRootFile /afs/cern.ch/work/g/gsaha/public/ChargedHiggsAnalysis/Analysis/data/POG_SFs/2018/Muon/RunABCD_SF_ISO.root
  - tightMuIsoSFhistName NUM_TightRelIso_DEN_MediumID_pt_abseta_syst
  ### EGammaID-ScaleFactors
  - electronLooseIdSFRootFile /afs/cern.ch/work/g/gsaha/public/ChargedHiggsAnalysis/Analysis/data/POG_SFs/2018/Electron_MVA/2018_ElectronMVA80iso.root
  - looseEleIdSFhistName EGamma_SF2D
  - electronTightIdSFRootFile /afs/cern.ch/work/g/gsaha/public/ChargedHiggsAnalysis/Analysis/data/POG_SFs/2018/Electron_MVA/2018_ElectronMVA90iso.root
  - tightEleIdSFhistName EGamma_SF2D
  ### FakeRates
  - FRRootFile /afs/cern.ch/work/g/gsaha/public/ChargedHiggsAnalysis/Analysis/data/FakeRates/2018/FR_lep_ttH_mva_2018_CERN_2019Jul08.root
  - muonFRhistName FR_mva085_mu_data_comb
  - electronFRhistName FR_mva080_el_data_comb
endInfo:
  - useEventList 0
  - eventId 1 895751 20

samplesDict:
  MC:
    ### DY-Jets
    DYJetsToLL_M-10to50:
      filedirs: 
        - /eos/user/s/sbaradia5/Analysis/post_processed/DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8
        - /eos/user/s/sbaradia5/Analysis/post_processed/DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8_ext1
      genEvtWtSum: 'genEventSumw'
      xsec: 18610.0
      filesPerJob: 4
      group: DY

    DYJetsToLL_M-50:
      filedirs:
        - /eos/user/s/sbaradia5/Analysis/post_processed/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8
        - /eos/user/s/sbaradia5/Analysis/post_processed/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8_ext2
      genEvtWtSum: 'genEventSumw'
      xsec: 6077.22 # pb
      filesPerJob: 4
      group: DY

    ### ttbar
    TTTo2L2Nu:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8
      genEvtWtSum: 'genEventSumw'
      xsec: 88.40
      filesPerJob: 2
      group: TT

    TTToSemiLeptonic: 
      filedirs: 
        - /eos/user/s/sbaradia5/Analysis/post_processed/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_ext3
        - /eos/user/s/sbaradia2/Analysis/post_processed/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8
      genEvtWtSum: 'genEventSumw'
      xsec: 365.52
      filesPerJob: 2
      group: TT

    TTToHadronic:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/TTToHadronic_TuneCP5_13TeV-powheg-pythia8
        - /eos/user/s/sbaradia2/Analysis/TTToHadronic_TuneCP5_13TeV-powheg-pythia8_ext2
      genEvtWtSum: 'genEventSumw'
      xsec: 377.85
      filesPerJob: 2
      group: TT

    ### Single-top
    ST_s-channel_4f:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/ST_s-channel_4f_leptonDecays
      genEvtWtSum: 'genEventSumw'
      xsec : 3.364
      filesPerJob: 2
      group: 'ST'

    ST_tW_top_5f:
      filedirs: 
        - /eos/user/s/sbaradia2/Analysis/post_processed/ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8
      genEvtWtSum: 'genEventSumw'
      xsec : 35.85
      filesPerJob: 4
      group: 'ST'

    ST_tW_antitop_5f:
      filedirs: 
        - /eos/user/s/sbaradia5/Analysis/post_processed/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8
      genEvtWtSum: 'genEventSumw'
      xsec : 35.85
      filesPerJob: 4
      group: 'ST'

    ST_t-channel_top_5f:
      filedirs: 
        - /eos/user/s/sbaradia2/Analysis/post_processed/ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8
      genEvtWtSum: 'genEventSumw'
      xsec : 136.02
      filesPerJob: 4
      group: 'ST'

    ST_t-channel_antitop_5f:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/ST_t-channel_antitop_4f_InclusiveDecays
      genEvtWtSum: 'genEventSumw'
      xsec : 80.95
      filesPerJob: 4
      group: 'ST'

    ##### Single Higgs
    ttHJetToNonbb:
      filedirs: 
        - /eos/user/s/sbaradia5/Analysis/post_processed/ttHJetToNonbb_M125_TuneCP5_13TeV_amcatnloFXFX_madspin_pythia8
      genEvtWtSum: 'genEventSumw'
      xsec: 0.2118
      filesPerJob: 4
      group: Rare

    ttHJetTobb:
      filedirs: 
        - /eos/user/s/sbaradia2/Analysis/post_processed/ttHJetTobb_M125_TuneCP5_13TeV_amcatnloFXFX_madspin_pythia8
      genEvtWtSum: 'genEventSumw'
      xsec: 0.2953
      filesPerJob: 4
      group: Rare

    ##### VV(V)
    ZZTo2L2Q:
      filedirs: 
        - /eos/user/s/sbaradia2/Analysis/post_processed/ZZTo2L2Q_13TeV_TuneCP5_amcatnloFXFX_madspin_pythia8_ext1
        - /eos/user/s/sbaradia5/Analysis/post_processed/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8
      genEvtWtSum: 'genEventSumw'
      xsec: 5.52
      filesPerJob: 4
      group: VV

    ZZTo2L2Nu:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/ZZTo2L2Nu_ext2
      genEvtWtSum: 'genEventSumw'
      xsec: 0.5644
      filesPerJob: 4
      group: VV

    ZZTo4L:
      filedirs: 
        - /eos/user/s/sbaradia5/Analysis/post_processed/ZZTo4L_13TeV_powheg_pythia8_TuneCP5
      genEvtWtSum: 'genEventSumw'
      xsec: 1.256
      filesPerJob: 4
      group: VV

    WWTo2L2Nu:
      filedirs: 
        - /eos/user/s/sbaradia5/Analysis/post_processed/WWTo2L2Nu_NNPDF31_TuneCP5_13TeV-powheg-pythia8
      genEvtWtSum: 'genEventSumw'
      xsec: 12.2
      filesPerJob: 4
      group: VV

    WWTo2L2Nu_DoubleScattering:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/WWTo2L2Nu_DoubleScattering
      genEvtWtSum: 'genEventSumw'
      xsec: 0.2232
      filesPerJob: 4
      group: VV

    WWToLNuQQ:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/WWToLNuQQ
      genEvtWtSum: 'genEventSumw'
      xsec: 43.53
      filesPerJob: 4
      group: VV

    WZTo3LNu:
      filedirs: 
        - /eos/user/s/sbaradia5/Analysis/post_processed/WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8
        - /eos/user/s/sbaradia3/Analysis/post_processed/WZTo3LNu_ext1
      genEvtWtSum: 'genEventSumw'
      xsec: 4.43
      filesPerJob: 4
      group: VV

    WZTo2L2Q:
      filedirs: 
        - /eos/user/s/sbaradia5/Analysis/post_processed/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8
      genEvtWtSum: 'genEventSumw'
      xsec: 5.6
      filesPerJob: 4
      group: VV

    WWW:
      filedirs: 
        - /eos/user/s/sbaradia5/Analysis/post_processed/WWW_4F_TuneCP5_13TeV-amcatnlo-pythia8
      genEvtWtSum: 'genEventSumw'
      xsec: 0.2086
      filesPerJob: 2
      group: VV

    WWZ:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/WWZ
      genEvtWtSum: 'genEventSumw'
      xsec: 0.1676
      filesPerJob: 2
      group: VV

    WZZ:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/WZZ
      genEvtWtSum: 'genEventSumw'
      xsec: 0.05701
      filesPerJob: 2
      group: VV

    ZZZ:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/ZZZ
      genEvtWtSum: 'genEventSumw'
      xsec: 0.01473
      filesPerJob: 2
      group: VV

    ##### WJets 
    ##### https://indico.cern.ch/event/673253/contributions/2756806/attachments/1541203/2416962/20171016_VJetsXsecsUpdate_PH-GEN.pdf
    WJetsToLNu_0J:
      filedirs: 
        - /eos/user/s/sbaradia5/Analysis/post_processed/WJetsToLNu_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8
      genEvtWtSum: 'genEventSumw'
      xsec: 49264.92
      filesPerJob: 2
      group: WJets

    WJetsToLNu_1J:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/WJetsToLNu_1J
      genEvtWtSum: 'genEventSumw'
      xsec: 8280.36
      filesPerJob: 2
      group: WJets

    WJetsToLNu_2J:
      filedirs: 
        - /eos/user/s/sbaradia2/Analysis/post_processed/WJetsToLNu_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8
      genEvtWtSum: 'genEventSumw'
      xsec: 3118.08
      filesPerJob: 2
      group: WJets

    ##### TTVX
    TTZToQQ:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/TTZToQQ
        - /eos/user/s/sbaradia3/Analysis/post_processed/TTZToQQ_ext1
      genEvtWtSum: 'genEventSumw'
      xsec: 0.5868
      filesPerJob: 2
      group: Rare

    TTWJetsToLNu:
      filedirs: 
        - /eos/user/s/sbaradia2/Analysis/TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8
      genEvtWtSum: 'genEventSumw'
      xsec: 0.196
      filesPerJob: 2
      group: Rare

    TTWJetsToQQ:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/TTWJetsToQQ
      genEvtWtSum: 'genEventSumw'
      xsec: 0.4049
      filesPerJob: 4
      group: Rare

    TTWW:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/TTWW_ext1
        - /eos/user/s/sbaradia3/Analysis/post_processed/TTWW_ext2
      genEvtWtSum: 'genEventSumw'
      xsec: 0.006981
      filesPerJob: 2
      group: Rare

    TTWH:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/TTWH
      genEvtWtSum: 'genEventSumw'
      xsec: 0.001582
      filesPerJob: 2
      group: Rare

    TTZH:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/TTZH
      genEvtWtSum: 'genEventSumw'
      xsec: 0.001535
      filesPerJob: 2
      group: Rare

    ##### Rares
    WpWpJJ:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/WpWpJJ_EWK-QCD
      genEvtWtSum: 'genEventSumw'
      xsec: 0.04926
      filesPerJob: 2
      group: Rare

    WZJJ:
      filedirs: 
        - /eos/user/s/sbaradia3/Analysis/post_processed/WZJJToLNu_EWK_QCD
      genEvtWtSum: 'genEventSumw'
      xsec: 0.4234
      filesPerJob: 2
      group: Rare

  DATA:  
    ### EGamma
    EGamma_2018A:
      filedirs: 
        - /eos/home-s/subirany/Exotic/NanoAOD/DATA/2018/EGamma/Run2018A-02Apr2020-v1
      filesPerJob: 20
      group: 'data'

    EGamma_2018B:
      filedirs: 
        - /eos/home-s/subirany/Exotic/NanoAOD/DATA/2018/EGamma/Run2018B-02Apr2020-v1
      filesPerJob: 20
      group: 'data'

    EGamma_2018C:
      filedirs: 
         - /eos/user/g/gsaha/Exotic/NanoAOD/DATA/2018/EGamma/Run2018C-02Apr2020-v1
      filesPerJob: 20
      group: 'data'

    EGamma_2018D:
      filedirs: 
        - /eos/home-s/subirany/Exotic/NanoAOD/DATA/2018/EGamma/Run2018D-02Apr2020-v1
      filesPerJob: 20
      group: 'data'


    ### MuonEG
    MuonEG_2018A:
      filedirs: 
        - /eos/user/g/gsaha3/Exotic/Data_NanoAOD_ReReco_02Apr2020/MuonEG/RunA
      filesPerJob: 20
      group: 'data'

    MuonEG_2018B:
      filedirs: 
        - /eos/user/g/gsaha3/Exotic/Data_NanoAOD_ReReco_02Apr2020/MuonEG/RunB
      filesPerJob: 20
      group: 'data'

    MuonEG_2018C:
      filedirs: 
        - /eos/user/g/gsaha3/Exotic/Data_NanoAOD_ReReco_02Apr2020/MuonEG/RunC
      filesPerJob: 20
      group: 'data'

    MuonEG_2018D:
      filedirs: 
        - /eos/user/g/gsaha3/Exotic/Data_NanoAOD_ReReco_02Apr2020/MuonEG/RunD
      filesPerJob: 20
      group: 'data'


    ### SingleMuon
    SingleMuon_2018A:
      filedirs: 
        - /eos/user/s/sbaradia4/Analysis/crab_output_ch_SingleMuon_data2018/SingleMuon_2018A
      filesPerJob: 20
      group: 'data'

    SingleMuon_2018B:
      filedirs: 
        - /eos/user/s/sbaradia4/Analysis/crab_output_ch_SingleMuon_data2018/SingleMuon_2018B
      filesPerJob: 20
      group: 'data'

    SingleMuon_2018C:
      filedirs: 
        - /eos/user/s/sbaradia4/Analysis/crab_output_ch_SingleMuon_data2018/SingleMuon_2018C
      filesPerJob: 20
      group: 'data'

    SingleMuon_2018D:
      filedirs: 
        - /eos/user/s/sbaradia4/Analysis/crab_output_ch_SingleMuon_data2018/SingleMuon_2018D
      filesPerJob: 20
      group: 'data'


    ### DoubleMuon
    DoubleMuon_2018A:
      filedirs: 
        - /eos/user/s/sarkar/Exotic/NanoAOD/DATA/2018/DoubleMuon/Run2018A-02Apr2020-v1
      filesPerJob: 20
      group: 'data'

    DoubleMuon_2018B:
      filedirs: 
        - /eos/user/s/sarkar/Exotic/NanoAOD/DATA/2018/DoubleMuon/Run2018B-02Apr2020-v1
      filesPerJob: 20
      group: 'data'

    DoubleMuon_2018C:
      filedirs: 
        - /eos/user/s/sarkar/Exotic/NanoAOD/DATA/2018/DoubleMuon/Run2018C-02Apr2020-v1
      filesPerJob: 20
      group: 'data'

    DoubleMuon_2018D:
      filedirs: 
        - /eos/user/s/sarkar/Exotic/NanoAOD/DATA/2018/DoubleMuon/Run2018D-02Apr2020-v1
      filesPerJob: 20
      group: 'data'

groupLegendInfo:
  DY:
    fill-color: '#20B2AA'
    legend: DY
    order: 1
  Rare:
    fill-color: '#9ACD32'
    legend: Rare
    order: 2
  TT:
    fill-color: '#BC8F8F'
    legend: t(t)+jets
    order: 6
  ST:
    fill-color: '#DDA0DD'
    legend: Single Top
    order: 3
  VV:
    fill-color: '#FA8072'
    legend: VV(V)
    order: 4
  WJets:
    fill-color: '#C0C0C0'
    legend: W + jets
    order: 5
  data:
    legend: data

legendPos:
  legend:
    position:
    - 0.33
    - 0.73
    - 0.95
    - 0.88