tree: Events
era: 2017
lumi: 41529.152 
appDir: /afs/cern.ch/work/g/gsaha/public/ChargedHiggsAnalysis/CMSSW_11_1_8/src
jobDir: /afs/cern.ch/work/g/gsaha/public/ChargedHiggsAnalysis
exeToRun: /afs/cern.ch/work/g/gsaha/public/ChargedHiggsAnalysis/Analysis/multileptonFake
outDir: /eos/user/g/gsaha5/Exotic
commonInfo:
  - readGenInfo 0
  - dumpGenInfo 0
  - readTrigObject 0
  - readPFObject 1
  - useLumiWt 1
  - dumpEventMax 10
  - logOption 0
  - maxEvent -1
  - nFiles -1
mvaInfo:
  - createMVATree 0
  - readMVA 0
  - MVAnetwork BDT_nT1500_D2_nC100_ns5
  - MVAxmlFile TMVAClassification_BDT_nT1500_D2_nC100_ns5.weights.xml
cutLists:
  - vtxCutList ndf=4 z=24 Rho=2
  - muonCutList eta=2.4 pt=10. dxy=0.05 dz=0.1 SIP3D=4. pfReliso=0.15
  - electronCutList pt=10. eta=2.5 dxyEB=0.05 dzEB=0.1 dxyEE=0.1 dzEE=0.2 SIP3D=4. pfReliso=0.20
  - tauCutList eta=2.3 pt=20. dz=0.2 muVeto=0.5 eleVeto=0.5 isol=0.5
  - jetCutList eta=2.5 pt=20. dRlep=0.4 btagFactor=0.8484
  - fatJetCutList eta=2.4 pt=200. dRlep=0.4 btagFactor=0.8484
  - photonCutList pt=2 eta=2.4 isol=1.8 dRmin=0.5 dRovEt2=0.012
  - evselCutList hLepPtMin=20. ZMassLow=60. ZMassHigh=120.
HLT_DoubleMuon:
  - Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8
  - Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass8
HLT_DoubleEG:
  - Ele23_Ele12_CaloIdL_TrackIdL_IsoVL
HLT_MuonEG:
  - Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
  - Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
  - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL
  - Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ
HLT_SingleMuon:
  - IsoMu24
  - IsoMu27
HLT_SingleElectron:
  - Ele35_WPTight_Gsf
  - Ele32_WPTight_Gsf
HLT_SingleElectronForFake:
  - HLT_Ele8_CaloIdM_TrackIdM_PFJet30
  - HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30
  - HLT_Ele17_CaloIdM_TrackIdM_PFJet30
HLT_SingleMuonForFake:
  - HLT_Mu8_TrkIsoVVL
  - HLT_Mu17_TrkIsoVVL
ScaleFactorsInfo:
  - muonIdSFRootFile /afs/cern.ch/work/g/gsaha/public/ChargedHiggsAnalysis/Analysis/data/POG_SFs/2017/RunBCDEF_SF_ID.root
  - looseMuonIdSFhistName NUM_LooseID_DEN_genTracks_pt_abseta
  - medMuonIdSFhistName NUM_MediumID_DEN_genTracks_pt_abseta
  - tightMuonIdSFhistName NUM_TightID_DEN_genTracks_pt_abseta
  - electronLooseIdSFRootFile /afs/cern.ch/work/g/gsaha/public/ChargedHiggsAnalysis/Analysis/data/POG_SFs/2017/egammaEffi_txt_EGM2D_MVA80noIso_UL17.root
  - looseEleIdSFhistName EGamma_SF2D
  - electronTightIdSFRootFile /afs/cern.ch/work/g/gsaha/public/ChargedHiggsAnalysis/Analysis/data/POG_SFs/2017/egammaEffi_txt_EGM2D_MVA90iso_UL17.root
  - tightEleIdSFhistName EGamma_SF2D
  - muonTightIsoSFRootFile /afs/cern.ch/work/g/gsaha/public/ChargedHiggsAnalysis/Analysis/data/POG_SFs/2017/RunBCDEF_SF_ISO.root
  - tightMuIsoSFhistName NUM_TightRelIso_DEN_MediumID_pt_abseta
endInfo:
  - useEventList 1
  - eventId 1 895751 20
samplesDict:
  MC:
    ### DY-Jets
    DYJetsToLL_M-50:
      filedirs: ['/eos/user/g/gsaha3/Exotic/MC_UL2017/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/']
      genEvtWtSum: 'genEventSumw'
      xsec: 6077.22 # pb
      filesPerJob: 2

    ### ttbar
    TTToSemiLeptonic: 
      filedirs: ['/eos/user/g/gsaha3/Exotic/MC_UL2017/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/']
      genEvtWtSum: 'genEventSumw'
      xsec: 365.52
      filesPerJob: 2

    TTTo2L2Nu:
      filedirs: ['/eos/user/g/gsaha3/Exotic/MC_UL2017/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/']
      genEvtWtSum: 'genEventSumw'
      xsec: 88.40
      filesPerJob: 2

    ST_s-channel_4f:
      filedirs: ['/eos/user/g/gsaha3/Exotic/MC_UL2017/ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-mcatnlo-pythia8']
      genEvtWtSum: 'genEventSumw'
      xsec : 3.364
      filesPerJob: 2

    ST_tW_top_5f:
      filedirs: ['/eos/user/g/gsaha3/Exotic/MC_UL2017/ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8']
      genEvtWtSum: 'genEventSumw'
      xsec : 35.85
      filesPerJob: 2

    ST_tW_antitop_5f:
      filedirs: ['/eos/user/g/gsaha3/Exotic/MC_UL2017/ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8']
      genEvtWtSum: 'genEventSumw'
      xsec : 35.85
      filesPerJob: 2

    TTWJetsToLNu:
      filedirs: ['/eos/user/g/gsaha3/Exotic/MC_UL2017/TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8']
      genEvtWtSum: 'genEventSumw'
      xsec : 0.1960
      filesPerJob: 3

    TTGJets:
      filedirs: ['/eos/user/g/gsaha3/Exotic/MC_UL2017/TTGJets_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8']
      genEvtWtSum: 'genEventSumw'
      xsec : 4.215
      filesPerJob: 2

    ST_t-channel_top_5f:
      filedirs: ['/eos/user/g/gsaha3/Exotic/MC_UL2017/ST_t-channel_top_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8']
      genEvtWtSum: 'genEventSumw'
      xsec : 136.02
      filesPerJob: 2

    ST_t-channel_antitop_5f:
      filedirs: ['/eos/user/g/gsaha3/Exotic/MC_UL2017/ST_t-channel_antitop_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8']
      genEvtWtSum: 'genEventSumw'
      xsec : 80.95
      filesPerJob: 2

  DATA:  
    ### era B
#    SingleMuon_2017B:
#      filedirs: ['/eos/user/p/ppalit3/Exotic/DATA/DoubleMuon2016/EraB/']
#      filesPerJob: 2

    SingleElectron_2017B:
      filedirs: ['/eos/user/g/gsaha3/Exotic/DATA_UL2017/SingleElectron/RunB']
      filesPerJob: 2

    SingleElectron_2017C:
      filedirs: ['/eos/user/g/gsaha3/Exotic/DATA_UL2017/SingleElectron/RunC']
      filesPerJob: 2

    SingleElectron_2017D:
      filedirs: ['/eos/user/g/gsaha3/Exotic/DATA_UL2017/SingleElectron/RunD']
      filesPerJob: 2

    SingleElectron_2017E:
      filedirs: ['/eos/user/g/gsaha3/Exotic/DATA_UL2017/SingleElectron/RunE']
      filesPerJob: 2

    SingleElectron_2017F:
      filedirs: ['/eos/user/g/gsaha3/Exotic/DATA_UL2017/SingleElectron/RunF']
      filesPerJob: 2


  SIGNAL:
#    Signal_PPAP_v1:
#      filedirs: ['/eos/user/p/ppalit3/Exotic/Signal_PPAP_BP1/']
#      xsec: 0.001929282841388
#      genEvtWtSum: 'genEventSumw'
#      filesPerJob: 100